spring.application.name=shopsphere
spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere_db
spring.datasource.username=root
spring.datasource.password=Shivam@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=ShopSphereSecretKeyForJwtAuthentication123456789